import { Game, Offer, User } from '@/types/app';

export const POPULAR_GAMES: Game[] = [
  {
    id: '1',
    name: 'Clash Royale',
    currency: 'Gems',
    icon: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Strategy',
    isPopular: true,
  },
  {
    id: '2',
    name: 'PUBG Mobile',
    currency: 'UC',
    icon: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Battle Royale',
    isPopular: true,
  },
  {
    id: '3',
    name: 'Candy Crush Saga',
    currency: 'Gold Bars',
    icon: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Puzzle',
    isPopular: true,
  },
  {
    id: '4',
    name: 'Free Fire',
    currency: 'Diamonds',
    icon: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Battle Royale',
    isPopular: true,
  },
  {
    id: '5',
    name: 'Coin Master',
    currency: 'Spins',
    icon: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Casual',
    isPopular: true,
  },
  {
    id: '6',
    name: 'Fortnite',
    currency: 'V-Bucks',
    icon: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Battle Royale',
  },
  {
    id: '7',
    name: 'Roblox',
    currency: 'Robux',
    icon: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Sandbox',
  },
  {
    id: '8',
    name: 'Minecraft',
    currency: 'Minecoins',
    icon: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Sandbox',
  },
];

export const SAMPLE_OFFERS: Offer[] = [
  {
    id: '1',
    title: 'Chime Mobile Banking App',
    description: 'Sign up for Chime and make your first deposit',
    reward: 420,
    type: 'signup',
    image: 'https://images.pexels.com/photos/669615/pexels-photo-669615.jpeg?auto=compress&cs=tinysrgb&w=400',
    timeEstimate: '5-10 min',
    difficulty: 'easy',
    isPremium: true,
    category: 'Finance',
  },
  {
    id: '2',
    title: 'Word Collect Game',
    description: 'Download and reach level 15',
    reward: 387.54,
    type: 'game',
    image: 'https://images.pexels.com/photos/278888/pexels-photo-278888.jpeg?auto=compress&cs=tinysrgb&w=400',
    timeEstimate: '30-45 min',
    difficulty: 'medium',
    category: 'Gaming',
  },
  {
    id: '3',
    title: 'Royal Match',
    description: 'Install and reach level 25',
    reward: 405.64,
    type: 'game',
    image: 'https://images.pexels.com/photos/278888/pexels-photo-278888.jpeg?auto=compress&cs=tinysrgb&w=400',
    timeEstimate: '45-60 min',
    difficulty: 'medium',
    category: 'Gaming',
  },
  {
    id: '4',
    title: 'Netflix Trial',
    description: 'Start your free trial subscription',
    reward: 1000,
    type: 'signup',
    image: 'https://images.pexels.com/photos/4009402/pexels-photo-4009402.jpeg?auto=compress&cs=tinysrgb&w=400',
    timeEstimate: '2-3 min',
    difficulty: 'easy',
    category: 'Entertainment',
  },
  {
    id: '5',
    title: 'Survey: Gaming Habits',
    description: 'Complete a 10-minute survey about your gaming preferences',
    reward: 150,
    type: 'survey',
    image: 'https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=400',
    timeEstimate: '10 min',
    difficulty: 'easy',
    category: 'Survey',
  },
  {
    id: '6',
    title: 'TikTok Account',
    description: 'Create account and follow 5 creators',
    reward: 200,
    type: 'app',
    image: 'https://images.pexels.com/photos/4050334/pexels-photo-4050334.jpeg?auto=compress&cs=tinysrgb&w=400',
    timeEstimate: '5 min',
    difficulty: 'easy',
    category: 'Social',
  },
];

export const SAMPLE_USER: User = {
  id: '1',
  username: 'Loot',
  email: 'user@lootplay.com',
  totalEarnings: 5.05,
  offersCompleted: 1,
  level: 0,
  referralCode: 'JPK2W',
  joinDate: new Date('2024-01-15'),
};